package catalog

func BuildCatalog() *Catalog {
	f := func(v float64) *float64 { return &v }

	return &Catalog{
		Models: []ModelEntry{
			// ==================== IMAGE ====================
			{
				ID:          "qwen-image-2.0-pro",
				Name:        "Qwen Image 2.0 Pro",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/multimodal-generation/generation",
				Async:       false,
				Description: "通义万相文生图旗舰模型",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "size", Label: "尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "steps", Label: "推理步数", Type: TypeInt, Default: 30, Min: f(1), Max: f(100)},
					{Name: "prompt_extend", Label: "提示词扩展", Type: TypeBool, Default: true},
					{Name: "negative_prompt", Label: "反向提示词", Type: TypeString},
				},
			},
			{
				ID:          "qwen-image-2.0",
				Name:        "Qwen Image 2.0",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/multimodal-generation/generation",
				Async:       false,
				Description: "通义万相文生图标准模型",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "size", Label: "尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "steps", Label: "推理步数", Type: TypeInt, Default: 30, Min: f(1), Max: f(100)},
					{Name: "prompt_extend", Label: "提示词扩展", Type: TypeBool, Default: true},
					{Name: "negative_prompt", Label: "反向提示词", Type: TypeString},
				},
			},
			{
				ID:          "wanx2.1-t2i-turbo",
				Name:        "Wanx 2.1 Turbo",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/text2image/image-synthesis",
				Async:       true,
				Description: "通义万相文生图极速版",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "size", Label: "尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "ref_img", Label: "参考图URL", Type: TypeMedia},
					{Name: "ref_strength", Label: "参考强度", Type: TypeFloat, Default: 0.5, Min: f(0), Max: f(1)},
					{Name: "negative_prompt", Label: "反向提示词", Type: TypeString},
				},
			},
			{
				ID:          "wan2.2-t2i",
				Name:        "Wan 2.2 文生图",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/text2image/image-synthesis",
				Async:       true,
				Description: "通义万相 Wan 2.2 文生图模型",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "size", Label: "尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "ref_img", Label: "参考图URL", Type: TypeMedia},
					{Name: "ref_strength", Label: "参考强度", Type: TypeFloat, Default: 0.5, Min: f(0), Max: f(1)},
					{Name: "negative_prompt", Label: "反向提示词", Type: TypeString},
				},
			},
			{
				ID:          "wanx-background-generation",
				Name:        "Wanx 背景生成",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/background-generation/generation",
				Async:       true,
				Description: "基于参考图生成背景替换",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "ref_img", Label: "原图URL", Type: TypeMedia, Required: true},
					{Name: "size", Label: "尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
				},
			},
			{
				ID:          "wanx-image-edit",
				Name:        "Wanx 图片编辑",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/image-edit/generation",
				Async:       true,
				Description: "基于提示词对图片进行编辑修改",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "编辑指令", Type: TypeString, Required: true},
					{Name: "ref_img", Label: "原图URL", Type: TypeMedia, Required: true},
					{Name: "size", Label: "输出尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
				},
			},
			{
				ID:          "wanx-sketch-to-image",
				Name:        "Wanx 涂鸦生图",
				Category:    CatImage,
				Endpoint:    "/api/v1/services/aigc/sketch-to-image/generation",
				Async:       true,
				Description: "根据草图/线稿生成精细图像",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "ref_img", Label: "草图URL", Type: TypeMedia, Required: true},
					{Name: "size", Label: "输出尺寸", Type: TypeSelect, Default: "1024*1024",
						Options: []Option{
							{"1024×1024 (1:1)", "1024*1024"},
							{"720×1280 (9:16)", "720*1280"},
							{"1280×720 (16:9)", "1280*720"},
						}},
					{Name: "n", Label: "生成数量", Type: TypeInt, Default: 1, Min: f(1), Max: f(4)},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
				},
			},

			// ==================== HAPPYHORSE VIDEO ====================
			{
				ID:          "happyhorse-1.0-t2v",
				Name:        "HappyHorse 文生视频",
				Category:    CatVideo,
				Endpoint:    "/api/v1/services/aigc/video-generation/video-synthesis",
				Async:       true,
				Description: "HappyHorse 文本生成视频，支持 3-15 秒高清视频",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true, Description: "不超过5000字符"},
					{Name: "resolution", Label: "分辨率", Type: TypeSelect, Default: "1080P",
						Options: []Option{{"1080P", "1080P"}, {"720P", "720P"}}},
					{Name: "duration", Label: "时长(秒)", Type: TypeInt, Default: 5, Min: f(3), Max: f(15)},
					{Name: "ratio", Label: "宽高比", Type: TypeSelect, Default: "16:9",
						Options: []Option{
							{"16:9", "16:9"}, {"9:16", "9:16"}, {"1:1", "1:1"},
							{"4:3", "4:3"}, {"3:4", "3:4"},
						}},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "watermark", Label: "水印", Type: TypeBool, Default: true},
					{Name: "audio_setting", Label: "声音", Type: TypeSelect, Default: "auto",
						Options: []Option{{"自动", "auto"}, {"保留原声", "origin"}}},
				},
			},
			{
				ID:          "happyhorse-1.0-i2v",
				Name:        "HappyHorse 图生视频",
				Category:    CatVideo,
				Endpoint:    "/api/v1/services/aigc/video-generation/video-synthesis",
				Async:       true,
				Description: "HappyHorse 图片生成视频，以首帧图驱动",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "first_frame", Label: "首帧图片", Type: TypeMedia, Required: true},
					{Name: "resolution", Label: "分辨率", Type: TypeSelect, Default: "1080P",
						Options: []Option{{"1080P", "1080P"}, {"720P", "720P"}}},
					{Name: "duration", Label: "时长(秒)", Type: TypeInt, Default: 5, Min: f(3), Max: f(15)},
					{Name: "ratio", Label: "宽高比", Type: TypeSelect, Default: "16:9",
						Options: []Option{
							{"16:9", "16:9"}, {"9:16", "9:16"}, {"1:1", "1:1"},
							{"4:3", "4:3"}, {"3:4", "3:4"},
						}},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "watermark", Label: "水印", Type: TypeBool, Default: true},
					{Name: "audio_setting", Label: "声音", Type: TypeSelect, Default: "auto",
						Options: []Option{{"自动", "auto"}, {"保留原声", "origin"}}},
				},
			},
			{
				ID:          "happyhorse-1.0-r2v",
				Name:        "HappyHorse 参考图生视频",
				Category:    CatVideo,
				Endpoint:    "/api/v1/services/aigc/video-generation/video-synthesis",
				Async:       true,
				Description: "HappyHorse 基于参考图生成视频，最多9张",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "提示词", Type: TypeString, Required: true},
					{Name: "ref_images", Label: "参考图片", Type: TypeMediaList, Required: true, Description: "1-9张图片URL，逗号分隔"},
					{Name: "resolution", Label: "分辨率", Type: TypeSelect, Default: "1080P",
						Options: []Option{{"1080P", "1080P"}, {"720P", "720P"}}},
					{Name: "duration", Label: "时长(秒)", Type: TypeInt, Default: 5, Min: f(3), Max: f(15)},
					{Name: "ratio", Label: "宽高比", Type: TypeSelect, Default: "16:9",
						Options: []Option{
							{"16:9", "16:9"}, {"9:16", "9:16"}, {"1:1", "1:1"},
							{"4:3", "4:3"}, {"3:4", "3:4"},
						}},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "watermark", Label: "水印", Type: TypeBool, Default: true},
					{Name: "audio_setting", Label: "声音", Type: TypeSelect, Default: "auto",
						Options: []Option{{"自动", "auto"}, {"保留原声", "origin"}}},
				},
			},
			{
				ID:          "happyhorse-1.0-video-edit",
				Name:        "HappyHorse 视频编辑",
				Category:    CatVideo,
				Endpoint:    "/api/v1/services/aigc/video-generation/video-synthesis",
				Async:       true,
				Description: "视频+参考图+指令完成风格变换、局部替换",
				Parameters: []ParamDef{
					{Name: "prompt", Label: "编辑指令", Type: TypeString, Required: true, Description: "风格转换、局部替换等"},
					{Name: "video_url", Label: "视频URL", Type: TypeMedia, Required: true, Description: "MP4/MOV，3-60秒，≤100MB"},
					{Name: "ref_images", Label: "参考图片", Type: TypeMediaList, Description: "0-5张图片URL，逗号分隔"},
					{Name: "resolution", Label: "分辨率", Type: TypeSelect, Default: "1080P",
						Options: []Option{{"1080P", "1080P"}, {"720P", "720P"}}},
					{Name: "seed", Label: "随机种子", Type: TypeInt, Min: f(0), Max: f(2147483647)},
					{Name: "watermark", Label: "水印", Type: TypeBool, Default: true},
					{Name: "audio_setting", Label: "声音控制", Type: TypeSelect, Default: "auto",
						Options: []Option{{"自动", "auto"}, {"保留原声", "origin"}},
						Description: "auto=模型自行控制, origin=保留原始声音"},
				},
			},
		},
	}
}